# density in g/cm^3
# heat in J/g/K
# boiling/melting in C

elements = {'Ac': {'M': '',
        'Z': 89,
        'abundance': '5.5x10-10',
        'block': 'f-block',
        'boiling': '3471',
        'config': '[Rn] 6d1 7s2',
        'density': '10.07',
        'electro_negativity': '1.1',
        'group': 'n/a',
        'heat': '0.12',
        'melting': '1323',
        'name': 'Actinium',
        'name_origin': "Greek aktis, 'ray'",
        'orgin': 'from decay',
        'period': '7',
        'phase': 'solid',
        'rad': '*'},
 'Ag': {'M': 107.87,
        'Z': 47,
        'abundance': '0.075',
        'block': 'd-block',
        'boiling': '2435',
        'config': '[Kr] 4d10 5s1',
        'density': '10.501',
        'electro_negativity': '1.93',
        'group': '11',
        'heat': '0.235',
        'melting': '1234.93',
        'name': 'Silver',
        'name_origin': 'English word Symbol Ag is derived from Latin argentum',
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Al': {'M': 26.982,
        'Z': 13,
        'abundance': '82300',
        'block': 'p-block',
        'boiling': '2792',
        'config': '[Ne] 3s2 3p1',
        'density': '2.698',
        'electro_negativity': '1.61',
        'group': '13',
        'heat': '0.897',
        'melting': '933.47',
        'name': 'Aluminium',
        'name_origin': "Alumina, from Latin alumen (gen. aluminis), 'bitter "
                       "salt, alum'",
        'orgin': 'primordial',
        'period': '3',
        'phase': 'solid',
        'rad': ''},
 'Am': {'M': '',
        'Z': 95,
        'abundance': '-',
        'block': 'f-block',
        'boiling': '2880',
        'config': '[Rn] 5f7 7s2',
        'density': '13.69',
        'electro_negativity': '1.13',
        'group': 'n/a',
        'heat': '-',
        'melting': '1449',
        'name': 'Americium',
        'name_origin': 'The Americas, where the element was first synthesised, '
                       'by analogy with its homologue europium',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'solid',
        'rad': '*'},
 'Ar': {'M': 39.95,
        'Z': 18,
        'abundance': '3.5',
        'block': 'p-block',
        'boiling': '87.30',
        'config': '[Ne] 3s2 3p6',
        'density': '0.0017837',
        'electro_negativity': '-',
        'group': '18',
        'heat': '0.52',
        'melting': '83.80',
        'name': 'Argon',
        'name_origin': "Greek argos, 'idle' (because of its inertness)",
        'orgin': 'primordial',
        'period': '3',
        'phase': 'gas',
        'rad': ''},
 'As': {'M': 74.922,
        'Z': 33,
        'abundance': '1.8',
        'block': 'p-block',
        'boiling': '887',
        'config': '[Ar] 3d10 4s2 4p3',
        'density': '5.776',
        'electro_negativity': '2.18',
        'group': '15',
        'heat': '0.329',
        'melting': '1090[l]',
        'name': 'Arsenic',
        'name_origin': "French arsenic, from Greek arsenikon 'yellow arsenic' "
                       "(influenced by arsenikos, 'masculine' or 'virile'), "
                       'from a West Asian wanderword ultimately from Old '
                       "Iranian *zarniya-ka, 'golden'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'At': {'M': '',
        'Z': 85,
        'abundance': '3x10-20',
        'block': 'p-block',
        'boiling': '610',
        'config': '[Xe] 4f14 5d10 6s2 6p5',
        'density': '7',
        'electro_negativity': '2.2',
        'group': '17',
        'heat': '-',
        'melting': '575',
        'name': 'Astatine',
        'name_origin': "Greek astatos, 'unstable'",
        'orgin': 'from decay',
        'period': '6',
        'phase': 'unknown phase',
        'rad': '*'},
 'Au': {'M': 196.97,
        'Z': 79,
        'abundance': '0.004',
        'block': 'd-block',
        'boiling': '3129',
        'config': '[Xe] 4f14 5d10 6s1',
        'density': '19.282',
        'electro_negativity': '2.54',
        'group': '11',
        'heat': '0.129',
        'melting': '1337.33',
        'name': 'Gold',
        'name_origin': 'English word Symbol Au is derived from Latin aurum',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'B': {'M': 10.81,
       'Z': 5,
       'abundance': '10',
       'block': 'p-block',
       'boiling': '4200',
       'config': '[He] 2s2 2p1',
       'density': '2.34',
       'electro_negativity': '2.04',
       'group': '13',
       'heat': '1.026',
       'melting': '2349',
       'name': 'Boron',
       'name_origin': 'Borax, a mineral (from Arabic bawraq)',
       'orgin': 'primordial',
       'period': '2',
       'phase': 'solid',
       'rad': ''},
 'Ba': {'M': 137.33,
        'Z': 56,
        'abundance': '425',
        'block': 's-block',
        'boiling': '2170',
        'config': '[Xe] 6s2',
        'density': '3.594',
        'electro_negativity': '0.89',
        'group': '2',
        'heat': '0.204',
        'melting': '1000',
        'name': 'Barium',
        'name_origin': "Greek barys, 'heavy'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Be': {'M': 9.0122,
        'Z': 4,
        'abundance': '2.8',
        'block': 's-block',
        'boiling': '2742',
        'config': '[He] 2s2',
        'density': '1.85',
        'electro_negativity': '1.57',
        'group': '2',
        'heat': '1.825',
        'melting': '1560',
        'name': 'Beryllium',
        'name_origin': 'Beryl, a mineral (ultimately from the name of Belur in '
                       'southern India)[4]',
        'orgin': 'primordial',
        'period': '2',
        'phase': 'solid',
        'rad': ''},
 'Bh': {'M': '',
        'Z': 107,
        'abundance': '-',
        'block': 'd-block',
        'boiling': '-',
        'config': '',
        'density': '(37.1)',
        'electro_negativity': '-',
        'group': '7',
        'heat': '-',
        'melting': '-',
        'name': 'Bohrium',
        'name_origin': 'Niels Bohr, Danish physicist',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'unknown phase',
        'rad': '*'},
 'Bi': {'M': 208.98,
        'Z': 83,
        'abundance': '0.009',
        'block': 'p-block',
        'boiling': '1837',
        'config': '[Xe] 4f14 5d10 6s2 6p3',
        'density': '9.807',
        'electro_negativity': '2.02',
        'group': '15',
        'heat': '0.122',
        'melting': '544.7',
        'name': 'Bismuth',
        'name_origin': "German Wismut, from weib Masse 'white mass', unless "
                       'from Arabic',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Bk': {'M': '',
        'Z': 97,
        'abundance': '-',
        'block': 'f-block',
        'boiling': '2900',
        'config': '',
        'density': '14.79',
        'electro_negativity': '1.3',
        'group': 'n/a',
        'heat': '-',
        'melting': '1259',
        'name': 'Berkelium',
        'name_origin': 'Berkeley, California, where the element was first '
                       'synthesised',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'solid',
        'rad': '*'},
 'Br': {'M': 79.904,
        'Z': 35,
        'abundance': '2.4',
        'block': 'p-block',
        'boiling': '332.0',
        'config': '[Ar] 3d10 4s2 4p5',
        'density': '3.122',
        'electro_negativity': '2.96',
        'group': '17',
        'heat': '0.474',
        'melting': '265.8',
        'name': 'Bromine',
        'name_origin': "Greek bromos, 'stench'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'liquid',
        'rad': ''},
 'C': {'M': 12.011,
       'Z': 6,
       'abundance': '200',
       'block': 'p-block',
       'boiling': '4300',
       'config': '[He] 2s2 2p2',
       'density': '2.267',
       'electro_negativity': '2.55',
       'group': '14',
       'heat': '0.709',
       'melting': '>4000',
       'name': 'Carbon',
       'name_origin': "Latin carbo, 'coal'",
       'orgin': 'primordial',
       'period': '2',
       'phase': 'solid',
       'rad': ''},
 'Ca': {'M': 40.078,
        'Z': 20,
        'abundance': '41500',
        'block': 's-block',
        'boiling': '1757',
        'config': '[Ar] 4s2',
        'density': '1.54',
        'electro_negativity': '1.00',
        'group': '2',
        'heat': '0.647',
        'melting': '1115',
        'name': 'Calcium',
        'name_origin': "Latin calx, 'lime'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'Cd': {'M': 112.41,
        'Z': 48,
        'abundance': '0.159',
        'block': 'd-block',
        'boiling': '1040',
        'config': '[Kr] 4d10 5s2',
        'density': '8.69',
        'electro_negativity': '1.69',
        'group': '12',
        'heat': '0.232',
        'melting': '594.22',
        'name': 'Cadmium',
        'name_origin': 'New Latin cadmia, from King Kadmos',
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Ce': {'M': 140.12,
        'Z': 58,
        'abundance': '66.5',
        'block': 'f-block',
        'boiling': '3716',
        'config': '[Xe] 4f1 5d1 6s2',
        'density': '6.77',
        'electro_negativity': '1.12',
        'group': 'n/a',
        'heat': '0.192',
        'melting': '1068',
        'name': 'Cerium',
        'name_origin': 'Ceres, a dwarf planet, considered a planet at the time',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Cf': {'M': '',
        'Z': 98,
        'abundance': '-',
        'block': 'f-block',
        'boiling': '(1743)[b]',
        'config': '',
        'density': '15.1',
        'electro_negativity': '1.3',
        'group': 'n/a',
        'heat': '-',
        'melting': '1173',
        'name': 'Californium',
        'name_origin': 'California, where the element was first synthesised in '
                       'the LBNL laboratory',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'solid',
        'rad': '*'},
 'Cl': {'M': 35.45,
        'Z': 17,
        'abundance': '145',
        'block': 'p-block',
        'boiling': '239.11',
        'config': '[Ne] 3s2 3p5',
        'density': '0.003214',
        'electro_negativity': '3.16',
        'group': '17',
        'heat': '0.479',
        'melting': '171.6',
        'name': 'Chlorine',
        'name_origin': "Greek chloros, 'greenish yellow'",
        'orgin': 'primordial',
        'period': '3',
        'phase': 'gas',
        'rad': ''},
 'Cm': {'M': '',
        'Z': 96,
        'abundance': '-',
        'block': 'f-block',
        'boiling': '3383',
        'config': '',
        'density': '13.51',
        'electro_negativity': '1.28',
        'group': 'n/a',
        'heat': '-',
        'melting': '1613',
        'name': 'Curium',
        'name_origin': 'Pierre Curie and Marie Curie, French physicists and '
                       'chemists',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'solid',
        'rad': '*'},
 'Co': {'M': 58.933,
        'Z': 27,
        'abundance': '25',
        'block': 'd-block',
        'boiling': '3200',
        'config': '[Ar] 3d7 4s2',
        'density': '8.86',
        'electro_negativity': '1.88',
        'group': '9',
        'heat': '0.421',
        'melting': '1768',
        'name': 'Cobalt',
        'name_origin': "German Kobold, 'goblin'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'Cr': {'M': 51.996,
        'Z': 24,
        'abundance': '102',
        'block': 'd-block',
        'boiling': '2944',
        'config': '[Ar] 3d5 4s1',
        'density': '7.15',
        'electro_negativity': '1.66',
        'group': '6',
        'heat': '0.449',
        'melting': '2180',
        'name': 'Chromium',
        'name_origin': "Greek chroma, 'colour'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'Cs': {'M': 132.91,
        'Z': 55,
        'abundance': '3',
        'block': 's-block',
        'boiling': '944',
        'config': '[Xe] 6s1',
        'density': '1.873',
        'electro_negativity': '0.79',
        'group': '1',
        'heat': '0.242',
        'melting': '301.59',
        'name': 'Caesium',
        'name_origin': "Latin caesius, 'sky-blue'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Cu': {'M': 63.546,
        'Z': 29,
        'abundance': '60',
        'block': 'd-block',
        'boiling': '2835',
        'config': '[Ar] 3d10 4s1',
        'density': '8.96',
        'electro_negativity': '1.90',
        'group': '11',
        'heat': '0.385',
        'melting': '1357.77',
        'name': 'Copper',
        'name_origin': 'English word, from Latin cuprum, from Ancient Greek '
                       "Kypros 'Cyprus'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'Db': {'M': '',
        'Z': 105,
        'abundance': '-',
        'block': 'd-block',
        'boiling': '-',
        'config': '',
        'density': '(29.3)',
        'electro_negativity': '-',
        'group': '5',
        'heat': '-',
        'melting': '-',
        'name': 'Dubnium',
        'name_origin': 'Dubna, Russia, where the element was discovered in the '
                       'JINR laboratory',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'unknown phase',
        'rad': '*'},
 'Dy': {'M': 162.5,
        'Z': 66,
        'abundance': '5.2',
        'block': 'f-block',
        'boiling': '2840',
        'config': '[Xe] 4f10 6s2',
        'density': '8.55',
        'electro_negativity': '1.22',
        'group': 'n/a',
        'heat': '0.17',
        'melting': '1680',
        'name': 'Dysprosium',
        'name_origin': "Greek dysprositos, 'hard to get'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Er': {'M': 167.26,
        'Z': 68,
        'abundance': '3.5',
        'block': 'f-block',
        'boiling': '3141',
        'config': '[Xe] 4f12 6s2',
        'density': '9.066',
        'electro_negativity': '1.24',
        'group': 'n/a',
        'heat': '0.168',
        'melting': '1802',
        'name': 'Erbium',
        'name_origin': 'Ytterby, Sweden, where it was found; see also yttrium, '
                       'terbium, ytterbium',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Es': {'M': '',
        'Z': 99,
        'abundance': '-',
        'block': 'f-block',
        'boiling': '(1269)',
        'config': '',
        'density': '8.84',
        'electro_negativity': '1.3',
        'group': 'n/a',
        'heat': '-',
        'melting': '1133',
        'name': 'Einsteinium',
        'name_origin': 'Albert Einstein, German physicist',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'solid',
        'rad': '*'},
 'Eu': {'M': 151.96,
        'Z': 63,
        'abundance': '2',
        'block': 'f-block',
        'boiling': '1802',
        'config': '[Xe] 4f7 6s2',
        'density': '5.243',
        'electro_negativity': '1.2',
        'group': 'n/a',
        'heat': '0.182',
        'melting': '1099',
        'name': 'Europium',
        'name_origin': 'Europe',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'F': {'M': 18.998,
       'Z': 9,
       'abundance': '585',
       'block': 'p-block',
       'boiling': '85.03',
       'config': '[He] 2s2 2p5',
       'density': '0.001696',
       'electro_negativity': '3.98',
       'group': '17',
       'heat': '0.824',
       'melting': '53.53',
       'name': 'Fluorine',
       'name_origin': "Latin fluere, 'to flow'",
       'orgin': 'primordial',
       'period': '2',
       'phase': 'gas',
       'rad': ''},
 'Fe': {'M': 55.845,
        'Z': 26,
        'abundance': '56300',
        'block': 'd-block',
        'boiling': '3134',
        'config': '[Ar] 3d6 4s2',
        'density': '7.874',
        'electro_negativity': '1.83',
        'group': '8',
        'heat': '0.449',
        'melting': '1811',
        'name': 'Iron',
        'name_origin': 'English word Symbol Fe is derived from Latin ferrum',
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'Fm': {'M': '',
        'Z': 100,
        'abundance': '-',
        'block': 'f-block',
        'boiling': '-',
        'config': '',
        'density': '(9.7)[b]',
        'electro_negativity': '1.3',
        'group': 'n/a',
        'heat': '-',
        'melting': '(1125)[b]',
        'name': 'Fermium',
        'name_origin': 'Enrico Fermi, Italian physicist',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'unknown phase',
        'rad': '*'},
 'Fr': {'M': '',
        'Z': 87,
        'abundance': '~ 1x10-18',
        'block': 's-block',
        'boiling': '890',
        'config': '[Rn] 7s1',
        'density': '1.87',
        'electro_negativity': '>0.79[6]',
        'group': '1',
        'heat': '-',
        'melting': '281',
        'name': 'Francium',
        'name_origin': 'France, home country of discoverer Marguerite Perey',
        'orgin': 'from decay',
        'period': '7',
        'phase': 'unknown phase',
        'rad': '*'},
 'Ga': {'M': 69.723,
        'Z': 31,
        'abundance': '19',
        'block': 'p-block',
        'boiling': '2673',
        'config': '[Ar] 3d10 4s2 4p1',
        'density': '5.907',
        'electro_negativity': '1.81',
        'group': '13',
        'heat': '0.371',
        'melting': '302.9146',
        'name': 'Gallium',
        'name_origin': "Latin Gallia, 'France'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'Gd': {'M': 157.25,
        'Z': 64,
        'abundance': '6.2',
        'block': 'f-block',
        'boiling': '3546',
        'config': '[Xe] 4f7 5d1 6s2',
        'density': '7.895',
        'electro_negativity': '1.2',
        'group': 'n/a',
        'heat': '0.236',
        'melting': '1585',
        'name': 'Gadolinium',
        'name_origin': 'Gadolinite, a mineral named after Johan Gadolin, '
                       'Finnish chemist, physicist and mineralogist',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Ge': {'M': 72.63,
        'Z': 32,
        'abundance': '1.5',
        'block': 'p-block',
        'boiling': '3106',
        'config': '[Ar] 3d10 4s2 4p2',
        'density': '5.323',
        'electro_negativity': '2.01',
        'group': '14',
        'heat': '0.32',
        'melting': '1211.40',
        'name': 'Germanium',
        'name_origin': "Latin Germania, 'Germany'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'H': {'M': 1.008,
       'Z': 1,
       'abundance': '1400',
       'block': 's-block',
       'boiling': '20.28',
       'config': '1s1',
       'density': '0.00008988',
       'electro_negativity': '2.20',
       'group': '1',
       'heat': '14.304',
       'melting': '14.01',
       'name': 'Hydrogen',
       'name_origin': "Greek elements hydro- and -gen, 'water-forming'",
       'orgin': 'primordial',
       'period': '1',
       'phase': 'gas',
       'rad': ''},
 'He': {'M': 4.0026,
        'Z': 2,
        'abundance': '0.008',
        'block': 's-block',
        'boiling': '4.22',
        'config': '1s2',
        'density': '0.0001785',
        'electro_negativity': '-',
        'group': '18',
        'heat': '5.193',
        'melting': '-[k]',
        'name': 'Helium',
        'name_origin': "Greek helios, 'sun'",
        'orgin': 'primordial',
        'period': '1',
        'phase': 'gas',
        'rad': ''},
 'Hf': {'M': 178.49,
        'Z': 72,
        'abundance': '3',
        'block': 'd-block',
        'boiling': '4876',
        'config': '[Xe] 4f14 5d2 6s2',
        'density': '13.31',
        'electro_negativity': '1.3',
        'group': '4',
        'heat': '0.144',
        'melting': '2506',
        'name': 'Hafnium',
        'name_origin': "New Latin Hafnia, 'Copenhagen' (from Danish havn, "
                       'harbour)',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Hg': {'M': 200.59,
        'Z': 80,
        'abundance': '0.085',
        'block': 'd-block',
        'boiling': '629.88',
        'config': '[Xe] 4f14 5d10 6s2',
        'density': '13.5336',
        'electro_negativity': '2.00',
        'group': '12',
        'heat': '0.14',
        'melting': '234.43',
        'name': 'Mercury',
        'name_origin': 'Mercury, Roman god of commerce, communication, and '
                       'luck, known for his speed and mobility Symbol Hg is '
                       'derived from its Latin name hydrargyrum, from Greek '
                       "hydrargyros, 'water-silver'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'liquid',
        'rad': ''},
 'Ho': {'M': 164.93,
        'Z': 67,
        'abundance': '1.3',
        'block': 'f-block',
        'boiling': '2993',
        'config': '[Xe] 4f11 6s2',
        'density': '8.795',
        'electro_negativity': '1.23',
        'group': 'n/a',
        'heat': '0.165',
        'melting': '1734',
        'name': 'Holmium',
        'name_origin': "New Latin Holmia, 'Stockholm'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Hs': {'M': '',
        'Z': 108,
        'abundance': '-',
        'block': 'd-block',
        'boiling': '-',
        'config': '',
        'density': '(40.7)',
        'electro_negativity': '-',
        'group': '8',
        'heat': '-',
        'melting': '-',
        'name': 'Hassium',
        'name_origin': "New Latin Hassia, 'Hesse', a state in Germany",
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'unknown phase',
        'rad': '*'},
 'I': {'M': 126.9,
       'Z': 53,
       'abundance': '0.45',
       'block': 'p-block',
       'boiling': '457.4',
       'config': '[Kr] 4d10 5s2 5p5',
       'density': '4.93',
       'electro_negativity': '2.66',
       'group': '17',
       'heat': '0.214',
       'melting': '386.85',
       'name': 'Iodine',
       'name_origin': "French iode, from Greek ioeides, 'violet'",
       'orgin': 'primordial',
       'period': '5',
       'phase': 'solid',
       'rad': ''},
 'In': {'M': 114.82,
        'Z': 49,
        'abundance': '0.25',
        'block': 'p-block',
        'boiling': '2345',
        'config': '[Kr] 4d10 5s2 5p1',
        'density': '7.31',
        'electro_negativity': '1.78',
        'group': '13',
        'heat': '0.233',
        'melting': '429.75',
        'name': 'Indium',
        'name_origin': "Latin indicum, 'indigo', the blue colour found in its "
                       'spectrum',
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Ir': {'M': 192.22,
        'Z': 77,
        'abundance': '0.001',
        'block': 'd-block',
        'boiling': '4701',
        'config': '[Xe] 4f14 5d7 6s2',
        'density': '22.56',
        'electro_negativity': '2.20',
        'group': '9',
        'heat': '0.131',
        'melting': '2719',
        'name': 'Iridium',
        'name_origin': 'Iris, the Greek goddess of the rainbow',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'K': {'M': 39.098,
       'Z': 19,
       'abundance': '20900',
       'block': 's-block',
       'boiling': '1032',
       'config': '[Ar] 4s1',
       'density': '0.862',
       'electro_negativity': '0.82',
       'group': '1',
       'heat': '0.757',
       'melting': '336.53',
       'name': 'Potassium',
       'name_origin': "New Latin potassa, 'potash', itself from pot and ash "
                      'Symbol K is derived from Latin kalium',
       'orgin': 'primordial',
       'period': '4',
       'phase': 'solid',
       'rad': ''},
 'Kr': {'M': 83.798,
        'Z': 36,
        'abundance': '1x10-4',
        'block': 'p-block',
        'boiling': '119.93',
        'config': '[Ar] 3d10 4s2 4p6',
        'density': '0.003733',
        'electro_negativity': '3.00',
        'group': '18',
        'heat': '0.248',
        'melting': '115.79',
        'name': 'Krypton',
        'name_origin': "Greek kryptos, 'hidden'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'gas',
        'rad': ''},
 'La': {'M': 138.91,
        'Z': 57,
        'abundance': '39',
        'block': 'f-block',
        'boiling': '3737',
        'config': '[Xe] 5d1 6s2',
        'density': '6.145',
        'electro_negativity': '1.1',
        'group': 'n/a',
        'heat': '0.195',
        'melting': '1193',
        'name': 'Lanthanum',
        'name_origin': "Greek lanthanein, 'to lie hidden'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Li': {'M': 6.94,
        'Z': 3,
        'abundance': '20',
        'block': 's-block',
        'boiling': '1560',
        'config': '[He] 2s1',
        'density': '0.534',
        'electro_negativity': '0.98',
        'group': '1',
        'heat': '3.582',
        'melting': '453.69',
        'name': 'Lithium',
        'name_origin': "Greek lithos, 'stone'",
        'orgin': 'primordial',
        'period': '2',
        'phase': 'solid',
        'rad': ''},
 'Lr': {'M': '',
        'Z': 103,
        'abundance': '-',
        'block': 'd-block',
        'boiling': '-',
        'config': '',
        'density': '(15.6)',
        'electro_negativity': '1.3',
        'group': '3',
        'heat': '-',
        'melting': '(1900)',
        'name': 'Lawrencium',
        'name_origin': 'Ernest Lawrence, American physicist',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'unknown phase',
        'rad': '*'},
 'Lu': {'M': 174.97,
        'Z': 71,
        'abundance': '0.8',
        'block': 'd-block',
        'boiling': '3675',
        'config': '[Xe] 4f14 5d1 6s2',
        'density': '9.84',
        'electro_negativity': '1.27',
        'group': '3',
        'heat': '0.154',
        'melting': '1925',
        'name': 'Lutetium',
        'name_origin': "Latin Lutetia, 'Paris'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Md': {'M': '',
        'Z': 101,
        'abundance': '-',
        'block': 'f-block',
        'boiling': '-',
        'config': '',
        'density': '(10.3)',
        'electro_negativity': '1.3',
        'group': 'n/a',
        'heat': '-',
        'melting': '(1100)',
        'name': 'Mendelevium',
        'name_origin': 'Dmitri Mendeleev, Russian chemist who proposed the '
                       'periodic table',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'unknown phase',
        'rad': '*'},
 'Mg': {'M': 24.305,
        'Z': 12,
        'abundance': '23300',
        'block': 's-block',
        'boiling': '1363',
        'config': '[Ne] 3s2',
        'density': '1.738',
        'electro_negativity': '1.31',
        'group': '2',
        'heat': '1.023',
        'melting': '923',
        'name': 'Magnesium',
        'name_origin': 'Magnesia, a district of Eastern Thessaly in Greece',
        'orgin': 'primordial',
        'period': '3',
        'phase': 'solid',
        'rad': ''},
 'Mn': {'M': 54.938,
        'Z': 25,
        'abundance': '950',
        'block': 'd-block',
        'boiling': '2334',
        'config': '[Ar] 3d5 4s2',
        'density': '7.44',
        'electro_negativity': '1.55',
        'group': '7',
        'heat': '0.479',
        'melting': '1519',
        'name': 'Manganese',
        'name_origin': 'Corrupted from magnesia negra; see magnesium',
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'Mo': {'M': 95.95,
        'Z': 42,
        'abundance': '1.2',
        'block': 'd-block',
        'boiling': '4912',
        'config': '[Kr] 4d5 5s1',
        'density': '10.22',
        'electro_negativity': '2.16',
        'group': '6',
        'heat': '0.251',
        'melting': '2896',
        'name': 'Molybdenum',
        'name_origin': "Greek molybdaina, 'piece of lead', from molybdos, "
                       "'lead', due to confusion with lead ore galena (PbS)",
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Mt': {'M': '',
        'Z': 109,
        'abundance': '-',
        'block': 'd-block',
        'boiling': '-',
        'config': '',
        'density': '(37.4)',
        'electro_negativity': '-',
        'group': '9',
        'heat': '-',
        'melting': '-',
        'name': 'Meitnerium',
        'name_origin': 'Lise Meitner, Austrian physicist',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'unknown phase',
        'rad': '*'},
 'N': {'M': 14.007,
       'Z': 7,
       'abundance': '19',
       'block': 'p-block',
       'boiling': '77.36',
       'config': '[He] 2s2 2p3',
       'density': '0.0012506',
       'electro_negativity': '3.04',
       'group': '15',
       'heat': '1.04',
       'melting': '63.15',
       'name': 'Nitrogen',
       'name_origin': "Greek nitron and -gen, 'niter-forming'",
       'orgin': 'primordial',
       'period': '2',
       'phase': 'gas',
       'rad': ''},
 'Na': {'M': 22.99,
        'Z': 11,
        'abundance': '23600',
        'block': 's-block',
        'boiling': '1156',
        'config': '[Ne] 3s1',
        'density': '0.971',
        'electro_negativity': '0.93',
        'group': '1',
        'heat': '1.228',
        'melting': '370.87',
        'name': 'Sodium',
        'name_origin': 'English (from medieval Latin) soda Symbol Na is '
                       'derived from New Latin natrium, coined from German '
                       "Natron, 'natron'",
        'orgin': 'primordial',
        'period': '3',
        'phase': 'solid',
        'rad': ''},
 'Nb': {'M': 92.906,
        'Z': 41,
        'abundance': '20',
        'block': 'd-block',
        'boiling': '5017',
        'config': '[Kr] 4d4 5s1',
        'density': '8.57',
        'electro_negativity': '1.6',
        'group': '5',
        'heat': '0.265',
        'melting': '2750',
        'name': 'Niobium',
        'name_origin': 'Niobe, daughter of king Tantalus from Greek mythology; '
                       'see also tantalum',
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Nd': {'M': 144.24,
        'Z': 60,
        'abundance': '41.5',
        'block': 'f-block',
        'boiling': '3347',
        'config': '[Xe] 4f4 6s2',
        'density': '7.007',
        'electro_negativity': '1.14',
        'group': 'n/a',
        'heat': '0.19',
        'melting': '1297',
        'name': 'Neodymium',
        'name_origin': "Greek neos didymos, 'new twin'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Ne': {'M': 20.18,
        'Z': 10,
        'abundance': '0.005',
        'block': 'p-block',
        'boiling': '27.07',
        'config': '[He] 2s2 2p6',
        'density': '0.0008999',
        'electro_negativity': '-',
        'group': '18',
        'heat': '1.03',
        'melting': '24.56',
        'name': 'Neon',
        'name_origin': "Greek neon, 'new'",
        'orgin': 'primordial',
        'period': '2',
        'phase': 'gas',
        'rad': ''},
 'Ni': {'M': 58.693,
        'Z': 28,
        'abundance': '84',
        'block': 'd-block',
        'boiling': '3186',
        'config': '[Ar] 3d8 4s2',
        'density': '8.912',
        'electro_negativity': '1.91',
        'group': '10',
        'heat': '0.444',
        'melting': '1728',
        'name': 'Nickel',
        'name_origin': 'Nickel, a mischievous sprite of German miner mythology',
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'No': {'M': '',
        'Z': 102,
        'abundance': '-',
        'block': 'f-block',
        'boiling': '-',
        'config': '',
        'density': '(9.9)',
        'electro_negativity': '1.3',
        'group': 'n/a',
        'heat': '-',
        'melting': '(1100)',
        'name': 'Nobelium',
        'name_origin': 'Alfred Nobel, Swedish chemist and engineer',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'unknown phase',
        'rad': '*'},
 'Np': {'M': '',
        'Z': 93,
        'abundance': '<= 3x10-12',
        'block': 'f-block',
        'boiling': '4273',
        'config': '[Rn] 5f4 6d1 7s2',
        'density': '20.45',
        'electro_negativity': '1.36',
        'group': 'n/a',
        'heat': '-',
        'melting': '917',
        'name': 'Neptunium',
        'name_origin': 'Neptune, the eighth planet in the Solar System',
        'orgin': 'from decay',
        'period': '7',
        'phase': 'solid',
        'rad': '*'},
 'O': {'M': 15.999,
       'Z': 8,
       'abundance': '461000',
       'block': 'p-block',
       'boiling': '90.20',
       'config': '[He] 2s2 2p4',
       'density': '0.001429',
       'electro_negativity': '3.44',
       'group': '16',
       'heat': '0.918',
       'melting': '54.36',
       'name': 'Oxygen',
       'name_origin': "Greek oxy- and -gen, 'acid-forming'",
       'orgin': 'primordial',
       'period': '2',
       'phase': 'gas',
       'rad': ''},
 'Os': {'M': 190.23,
        'Z': 76,
        'abundance': '0.002',
        'block': 'd-block',
        'boiling': '5285',
        'config': '[Xe] 4f14 5d6 6s2',
        'density': '22.61',
        'electro_negativity': '2.2',
        'group': '8',
        'heat': '0.13',
        'melting': '3306',
        'name': 'Osmium',
        'name_origin': "Greek osme, 'smell'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'P': {'M': 30.974,
       'Z': 15,
       'abundance': '1050',
       'block': 'p-block',
       'boiling': '550',
       'config': '[Ne] 3s2 3p3',
       'density': '1.82',
       'electro_negativity': '2.19',
       'group': '15',
       'heat': '0.769',
       'melting': '317.30',
       'name': 'Phosphorus',
       'name_origin': "Greek phosphoros, 'light-bearing'",
       'orgin': 'primordial',
       'period': '3',
       'phase': 'solid',
       'rad': ''},
 'Pa': {'M': 231.04,
        'Z': 91,
        'abundance': '1.4x10-6',
        'block': 'f-block',
        'boiling': '4300',
        'config': '[Rn] 5f2 6d1 7s2',
        'density': '15.37',
        'electro_negativity': '1.5',
        'group': 'n/a',
        'heat': '-',
        'melting': '1841',
        'name': 'Protactinium',
        'name_origin': "Proto- (from Greek protos, 'first, before') + "
                       'actinium, since actinium is produced through the '
                       'radioactive decay of protactinium',
        'orgin': 'from decay',
        'period': '7',
        'phase': 'solid',
        'rad': ''},
 'Pb': {'M': 207.2,
        'Z': 82,
        'abundance': '14',
        'block': 'p-block',
        'boiling': '2022',
        'config': '[Xe] 4f14 5d10 6s2 6p2',
        'density': '11.342',
        'electro_negativity': '1.87 (2+)2.33 (4+)',
        'group': '14',
        'heat': '0.129',
        'melting': '600.61',
        'name': 'Lead',
        'name_origin': 'English word Symbol Pb is derived from Latin plumbum',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Pd': {'M': 106.42,
        'Z': 46,
        'abundance': '0.015',
        'block': 'd-block',
        'boiling': '3236',
        'config': '[Kr] 4d10',
        'density': '12.02',
        'electro_negativity': '2.20',
        'group': '10',
        'heat': '0.244',
        'melting': '1828.05',
        'name': 'Palladium',
        'name_origin': 'Pallas, an asteroid, considered a planet at the time',
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Pm': {'M': '',
        'Z': 61,
        'abundance': '2x10-19',
        'block': 'f-block',
        'boiling': '3273',
        'config': '[Xe] 4f5 6s2',
        'density': '7.26',
        'electro_negativity': '1.13',
        'group': 'n/a',
        'heat': '-',
        'melting': '1315',
        'name': 'Promethium',
        'name_origin': 'Prometheus, a figure in Greek mythology',
        'orgin': 'from decay',
        'period': '6',
        'phase': 'solid',
        'rad': '*'},
 'Po': {'M': '',
        'Z': 84,
        'abundance': '2x10-10',
        'block': 'p-block',
        'boiling': '1235',
        'config': '[Xe] 4f14 5d10 6s2 6p4',
        'density': '9.32',
        'electro_negativity': '2.0',
        'group': '16',
        'heat': '-',
        'melting': '527',
        'name': 'Polonium',
        'name_origin': "Latin Polonia, 'Poland', home country of Marie Curie",
        'orgin': 'from decay',
        'period': '6',
        'phase': 'solid',
        'rad': '*'},
 'Pr': {'M': 140.91,
        'Z': 59,
        'abundance': '9.2',
        'block': 'f-block',
        'boiling': '3793',
        'config': '[Xe] 4f3 6s2',
        'density': '6.773',
        'electro_negativity': '1.13',
        'group': 'n/a',
        'heat': '0.193',
        'melting': '1208',
        'name': 'Praseodymium',
        'name_origin': "Greek prasios didymos, 'green twin'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Pt': {'M': 195.08,
        'Z': 78,
        'abundance': '0.005',
        'block': 'd-block',
        'boiling': '4098',
        'config': '[Xe] 4f14 5d9 6s1',
        'density': '21.46',
        'electro_negativity': '2.28',
        'group': '10',
        'heat': '0.133',
        'melting': '2041.4',
        'name': 'Platinum',
        'name_origin': "Spanish platina, 'little silver', from plata 'silver'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Pu': {'M': '',
        'Z': 94,
        'abundance': '<= 3x10-11',
        'block': 'f-block',
        'boiling': '3501',
        'config': '[Rn] 5f6 7s2',
        'density': '19.84',
        'electro_negativity': '1.28',
        'group': 'n/a',
        'heat': '-',
        'melting': '912.5',
        'name': 'Plutonium',
        'name_origin': 'Pluto, a dwarf planet, considered a planet in the '
                       'Solar System at the time',
        'orgin': 'from decay',
        'period': '7',
        'phase': 'solid',
        'rad': '*'},
 'Ra': {'M': '',
        'Z': 88,
        'abundance': '9x10-7',
        'block': 's-block',
        'boiling': '2010',
        'config': '[Rn] 7s2',
        'density': '5.5',
        'electro_negativity': '0.9',
        'group': '2',
        'heat': '0.094',
        'melting': '973',
        'name': 'Radium',
        'name_origin': "French radium, from Latin radius, 'ray'",
        'orgin': 'from decay',
        'period': '7',
        'phase': 'solid',
        'rad': '*'},
 'Rb': {'M': 85.468,
        'Z': 37,
        'abundance': '90',
        'block': 's-block',
        'boiling': '961',
        'config': '[Kr] 5s1',
        'density': '1.532',
        'electro_negativity': '0.82',
        'group': '1',
        'heat': '0.363',
        'melting': '312.46',
        'name': 'Rubidium',
        'name_origin': "Latin rubidus, 'deep red'",
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Re': {'M': 186.21,
        'Z': 75,
        'abundance': '7x10-4',
        'block': 'd-block',
        'boiling': '5869',
        'config': '[Xe] 4f14 5d5 6s2',
        'density': '21.02',
        'electro_negativity': '1.9',
        'group': '7',
        'heat': '0.137',
        'melting': '3459',
        'name': 'Rhenium',
        'name_origin': "Latin Rhenus, 'the Rhine'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Rf': {'M': '',
        'Z': 104,
        'abundance': '-',
        'block': 'd-block',
        'boiling': '(5800)',
        'config': '',
        'density': '(23.2)',
        'electro_negativity': '-',
        'group': '4',
        'heat': '-',
        'melting': '(2400)',
        'name': 'Rutherfordium',
        'name_origin': 'Ernest Rutherford, chemist and physicist from New '
                       'Zealand',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'unknown phase',
        'rad': '*'},
 'Rh': {'M': 102.91,
        'Z': 45,
        'abundance': '0.001',
        'block': 'd-block',
        'boiling': '3968',
        'config': '[Kr] 4d8 5s1',
        'density': '12.41',
        'electro_negativity': '2.28',
        'group': '9',
        'heat': '0.243',
        'melting': '2237',
        'name': 'Rhodium',
        'name_origin': "Greek rhodoeis, 'rose-coloured', from rhodon, 'rose'",
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Rn': {'M': '',
        'Z': 86,
        'abundance': '4x10-13',
        'block': 'p-block',
        'boiling': '211.3',
        'config': '[Xe] 4f14 5d10 6s2 6p6',
        'density': '0.00973',
        'electro_negativity': '2.2',
        'group': '18',
        'heat': '0.094',
        'melting': '202',
        'name': 'Radon',
        'name_origin': 'Radium emanation, originally the name of the isotope '
                       'Radon-222',
        'orgin': 'from decay',
        'period': '6',
        'phase': 'gas',
        'rad': '*'},
 'Ru': {'M': 101.07,
        'Z': 44,
        'abundance': '0.001',
        'block': 'd-block',
        'boiling': '4423',
        'config': '[Kr] 4d7 5s1',
        'density': '12.37',
        'electro_negativity': '2.2',
        'group': '8',
        'heat': '0.238',
        'melting': '2607',
        'name': 'Ruthenium',
        'name_origin': "New Latin Ruthenia, 'Russia'",
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'S': {'M': 32.06,
       'Z': 16,
       'abundance': '350',
       'block': 'p-block',
       'boiling': '717.87',
       'config': '[Ne] 3s2 3p4',
       'density': '2.067',
       'electro_negativity': '2.58',
       'group': '16',
       'heat': '0.71',
       'melting': '388.36',
       'name': 'Sulfur',
       'name_origin': "Latin sulphur, 'brimstone'",
       'orgin': 'primordial',
       'period': '3',
       'phase': 'solid',
       'rad': ''},
 'Sb': {'M': 121.76,
        'Z': 51,
        'abundance': '0.2',
        'block': 'p-block',
        'boiling': '1860',
        'config': '[Kr] 4d10 5s2 5p3',
        'density': '6.685',
        'electro_negativity': '2.05',
        'group': '15',
        'heat': '0.207',
        'melting': '903.78',
        'name': 'Antimony',
        'name_origin': 'Latin antimonium, the origin of which is uncertain: '
                       'folk etymologies suggest it is derived from Greek anti '
                       "('against') + monos ('alone'), or Old French "
                       "anti-moine, 'Monk's bane', but it could plausibly be "
                       "from or related to Arabic itmid, 'antimony', "
                       'reformatted as a Latin word Symbol Sb is derived from '
                       "Latin stibium 'stibnite'",
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Sc': {'M': 44.956,
        'Z': 21,
        'abundance': '22',
        'block': 'd-block',
        'boiling': '3109',
        'config': '[Ar] 3d1 4s2',
        'density': '2.989',
        'electro_negativity': '1.36',
        'group': '3',
        'heat': '0.568',
        'melting': '1814',
        'name': 'Scandium',
        'name_origin': "Latin Scandia, 'Scandinavia'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'Se': {'M': 78.971,
        'Z': 34,
        'abundance': '0.05',
        'block': 'p-block',
        'boiling': '958',
        'config': '[Ar] 3d10 4s2 4p4',
        'density': '4.809',
        'electro_negativity': '2.55',
        'group': '16',
        'heat': '0.321',
        'melting': '453',
        'name': 'Selenium',
        'name_origin': "Greek selene, 'moon'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'Sg': {'M': '',
        'Z': 106,
        'abundance': '-',
        'block': 'd-block',
        'boiling': '-',
        'config': '',
        'density': '(35.0)',
        'electro_negativity': '-',
        'group': '6',
        'heat': '-',
        'melting': '-',
        'name': 'Seaborgium',
        'name_origin': 'Glenn T. Seaborg, American chemist',
        'orgin': 'synthetic',
        'period': '7',
        'phase': 'unknown phase',
        'rad': '*'},
 'Si': {'M': 28.085,
        'Z': 14,
        'abundance': '282000',
        'block': 'p-block',
        'boiling': '3538',
        'config': '[Ne] 3s2 3p2',
        'density': '2.3296',
        'electro_negativity': '1.9',
        'group': '14',
        'heat': '0.705',
        'melting': '1687',
        'name': 'Silicon',
        'name_origin': "Latin silex, 'flint' (originally silicium)",
        'orgin': 'primordial',
        'period': '3',
        'phase': 'solid',
        'rad': ''},
 'Sm': {'M': 150.36,
        'Z': 62,
        'abundance': '7.05',
        'block': 'f-block',
        'boiling': '2067',
        'config': '[Xe] 4f6 6s2',
        'density': '7.52',
        'electro_negativity': '1.17',
        'group': 'n/a',
        'heat': '0.197',
        'melting': '1345',
        'name': 'Samarium',
        'name_origin': 'Samarskite, a mineral named after V. '
                       'Samarsky-Bykhovets, Russian mine official',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Sn': {'M': 118.71,
        'Z': 50,
        'abundance': '2.3',
        'block': 'p-block',
        'boiling': '2875',
        'config': '[Kr] 4d10 5s2 5p2',
        'density': '7.287',
        'electro_negativity': '1.96',
        'group': '14',
        'heat': '0.228',
        'melting': '505.08',
        'name': 'Tin',
        'name_origin': 'English word Symbol Sn is derived from Latin stannum',
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Sr': {'M': 87.62,
        'Z': 38,
        'abundance': '370',
        'block': 's-block',
        'boiling': '1655',
        'config': '[Kr] 5s2',
        'density': '2.64',
        'electro_negativity': '0.95',
        'group': '2',
        'heat': '0.301',
        'melting': '1050',
        'name': 'Strontium',
        'name_origin': 'Strontian, a village in Scotland, where it was found',
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Ta': {'M': 180.95,
        'Z': 73,
        'abundance': '2',
        'block': 'd-block',
        'boiling': '5731',
        'config': '[Xe] 4f14 5d3 6s2',
        'density': '16.654',
        'electro_negativity': '1.5',
        'group': '5',
        'heat': '0.14',
        'melting': '3290',
        'name': 'Tantalum',
        'name_origin': 'King Tantalus, father of Niobe from Greek mythology; '
                       'see also niobium',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Tb': {'M': 158.93,
        'Z': 65,
        'abundance': '1.2',
        'block': 'f-block',
        'boiling': '3503',
        'config': '[Xe] 4f9 6s2',
        'density': '8.229',
        'electro_negativity': '1.2',
        'group': 'n/a',
        'heat': '0.182',
        'melting': '1629',
        'name': 'Terbium',
        'name_origin': 'Ytterby, Sweden, where it was found; see also yttrium, '
                       'erbium, ytterbium',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Tc': {'M': '',
        'Z': 43,
        'abundance': '~ 3x10-9',
        'block': 'd-block',
        'boiling': '4538',
        'config': '[Kr] 4d5 5s2',
        'density': '11.5',
        'electro_negativity': '1.9',
        'group': '7',
        'heat': '-',
        'melting': '2430',
        'name': 'Technetium',
        'name_origin': "Greek tekhnetos, 'artificial'",
        'orgin': 'from decay',
        'period': '5',
        'phase': 'solid',
        'rad': '*'},
 'Te': {'M': 127.6,
        'Z': 52,
        'abundance': '0.001',
        'block': 'p-block',
        'boiling': '1261',
        'config': '[Kr] 4d10 5s2 5p4',
        'density': '6.232',
        'electro_negativity': '2.1',
        'group': '16',
        'heat': '0.202',
        'melting': '722.66',
        'name': 'Tellurium',
        'name_origin': "Latin tellus, 'the ground, earth'",
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''},
 'Th': {'M': 232.04,
        'Z': 90,
        'abundance': '9.6',
        'block': 'f-block',
        'boiling': '5061',
        'config': '[Rn] 6d2 7s2',
        'density': '11.72',
        'electro_negativity': '1.3',
        'group': 'n/a',
        'heat': '0.113',
        'melting': '2115',
        'name': 'Thorium',
        'name_origin': 'Thor, the Scandinavian god of thunder',
        'orgin': 'primordial',
        'period': '7',
        'phase': 'solid',
        'rad': ''},
 'Ti': {'M': 47.867,
        'Z': 22,
        'abundance': '5650',
        'block': 'd-block',
        'boiling': '3560',
        'config': '[Ar] 3d2 4s2',
        'density': '4.54',
        'electro_negativity': '1.54',
        'group': '4',
        'heat': '0.523',
        'melting': '1941',
        'name': 'Titanium',
        'name_origin': 'Titans, the sons of the Earth goddess of Greek '
                       'mythology',
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'Tl': {'M': 204.38,
        'Z': 81,
        'abundance': '0.85',
        'block': 'p-block',
        'boiling': '1746',
        'config': '[Xe] 4f14 5d10 6s2 6p1',
        'density': '11.85',
        'electro_negativity': '1.62',
        'group': '13',
        'heat': '0.129',
        'melting': '577',
        'name': 'Thallium',
        'name_origin': "Greek thallos, 'green shoot or twig'",
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Tm': {'M': 168.93,
        'Z': 69,
        'abundance': '0.52',
        'block': 'f-block',
        'boiling': '2223',
        'config': '[Xe] 4f13 6s2',
        'density': '9.321',
        'electro_negativity': '1.25',
        'group': 'n/a',
        'heat': '0.16',
        'melting': '1818',
        'name': 'Thulium',
        'name_origin': 'Thule, the ancient name for an unclear northern '
                       'location',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'U': {'M': 238.03,
       'Z': 92,
       'abundance': '2.7',
       'block': 'f-block',
       'boiling': '4404',
       'config': '[Rn] 5f3 6d1 7s2',
       'density': '18.95',
       'electro_negativity': '1.38',
       'group': 'n/a',
       'heat': '0.116',
       'melting': '1405.3',
       'name': 'Uranium',
       'name_origin': 'Uranus, the seventh planet in the Solar System',
       'orgin': 'primordial',
       'period': '7',
       'phase': 'solid',
       'rad': ''},
 'V': {'M': 50.942,
       'Z': 23,
       'abundance': '120',
       'block': 'd-block',
       'boiling': '3680',
       'config': '[Ar] 3d3 4s2',
       'density': '6.11',
       'electro_negativity': '1.63',
       'group': '5',
       'heat': '0.489',
       'melting': '2183',
       'name': 'Vanadium',
       'name_origin': 'Vanadis, an Old Norse name for the Scandinavian goddess '
                      'Freyja',
       'orgin': 'primordial',
       'period': '4',
       'phase': 'solid',
       'rad': ''},
 'W': {'M': 183.84,
       'Z': 74,
       'abundance': '1.3',
       'block': 'd-block',
       'boiling': '5828',
       'config': '[Xe] 4f14 5d4 6s2',
       'density': '19.25',
       'electro_negativity': '2.36',
       'group': '6',
       'heat': '0.132',
       'melting': '3695',
       'name': 'Tungsten',
       'name_origin': "Swedish tung sten, 'heavy stone' Symbol W is from "
                      'Wolfram, originally from Middle High German wolf-rahm '
                      "'wolf's foam' describing the mineral wolframite[5]",
       'orgin': 'primordial',
       'period': '6',
       'phase': 'solid',
       'rad': ''},
 'Xe': {'M': 131.29,
        'Z': 54,
        'abundance': '3x10-5',
        'block': 'p-block',
        'boiling': '165.03',
        'config': '[Kr] 4d10 5s2 5p6',
        'density': '0.005887',
        'electro_negativity': '2.60',
        'group': '18',
        'heat': '0.158',
        'melting': '161.4',
        'name': 'Xenon',
        'name_origin': "Greek xenon, neuter form of xenos 'strange'",
        'orgin': 'primordial',
        'period': '5',
        'phase': 'gas',
        'rad': ''},
 'Y': {'M': 88.906,
       'Z': 39,
       'abundance': '33',
       'block': 'd-block',
       'boiling': '3609',
       'config': '[Kr] 4d1 5s2',
       'density': '4.469',
       'electro_negativity': '1.22',
       'group': '3',
       'heat': '0.298',
       'melting': '1799',
       'name': 'Yttrium',
       'name_origin': 'Ytterby, Sweden, where it was found; see also terbium, '
                      'erbium, ytterbium',
       'orgin': 'primordial',
       'period': '5',
       'phase': 'solid',
       'rad': ''},
 'Yb': {'M': 173.05,
        'Z': 70,
        'abundance': '3.2',
        'block': 'f-block',
        'boiling': '1469',
        'config': '[Xe] 4f14 6s2',
        'density': '6.965',
        'electro_negativity': '1.1',
        'group': 'n/a',
        'heat': '0.155',
        'melting': '1097',
        'name': 'Ytterbium',
        'name_origin': 'Ytterby, Sweden, where it was found; see also yttrium, '
                       'terbium, erbium',
        'orgin': 'primordial',
        'period': '6',
        'phase': 'solid',
        'rad': ''},
 'Zn': {'M': 65.38,
        'Z': 30,
        'abundance': '70',
        'block': 'd-block',
        'boiling': '1180',
        'config': '[Ar] 3d10 4s2',
        'density': '7.134',
        'electro_negativity': '1.65',
        'group': '12',
        'heat': '0.388',
        'melting': '692.88',
        'name': 'Zinc',
        'name_origin': "Most likely from German Zinke, 'prong' or 'tooth', "
                       "though some suggest Persian sang, 'stone'",
        'orgin': 'primordial',
        'period': '4',
        'phase': 'solid',
        'rad': ''},
 'Zr': {'M': 91.224,
        'Z': 40,
        'abundance': '165',
        'block': 'd-block',
        'boiling': '4682',
        'config': '[Kr] 4d2 5s2',
        'density': '6.506',
        'electro_negativity': '1.33',
        'group': '4',
        'heat': '0.278',
        'melting': '2128',
        'name': 'Zirconium',
        'name_origin': "Zircon, a mineral, from Persian zargun, 'gold-hued'",
        'orgin': 'primordial',
        'period': '5',
        'phase': 'solid',
        'rad': ''}}